name: Moodle Autograder CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengambil kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Langkah 3: Menginstall semua library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pytest-json-report

      # Langkah 4: Menjalankan tes dan membuat laporan JSON
      - name: Run tests with pytest
        id: run-tests
        run: |
          # Perintah ini akan membuat report.json jika ada file tes
          pytest --json-report --json-report-file=report.json || true
      
      # Langkah 5: Menjalankan skrip Python untuk mengirim nilai ke Moodle
      - name: Grade and Post to Moodle
        run: |
          python .github/workflows/grade_poster.py
        env:
          # Melewatkan Token (dari secrets) dan Username GitHub (otomatis) ke skrip
          MOODLE_TOKEN: ${{ secrets.MOODLE_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
