name: Moodle Autograder CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests with pytest
        id: run-tests
        run: |
          # Perintah ini membuat report.json jika tes ada dan berhasil dijalankan
          pytest --json-report --json-report-file=report.json || true
      
      - name: Grade and Post to Moodle
        run: |
          python .github/workflows/grade_poster.py
        env:
          # Melewatkan token dan username dari GitHub ke dalam skrip
          MOODLE_TOKEN: ${{ secrets.MOODLE_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
